name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # === auth-service ===
      - name: Install Dependencies (auth-service)
        run: |
          cd auth-service
          npm install

      - name: Run Snyk Scan (auth-service)
        run: |
          cd auth-service
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # === api-gateway ===
      - name: Install Dependencies (api-gateway)
        run: |
          cd api-gateway
          npm install

      - name: Run Snyk Scan (api-gateway)
        run: |
          cd api-gateway
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
